wp <- read.csv('hydroBdata/waterPotential.csv')
wp$Date <- ymd(as.character(wp$Date))
wp$nday <- as.numeric(wp$Date-as.Date("2018-05-15"))
pd <- subset(wp, time=='predawn')
pdSumm <- doBy::summaryBy()